version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 3
    labels:
      - dependencies
    commit-message:
      prefix: deps(go)
    groups:
      go-minor-and-patch:
        update-types:
          - minor
          - patch
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Etc/UTC
    open-pull-requests-limit: 3
    labels:
      - dependencies
    commit-message:
      prefix: deps(frontend)
    groups:
      frontend-minor-and-patch:
        update-types:
          - minor
          - patch
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 2
    labels:
      - dependencies
    commit-message:
      prefix: deps(container)
    groups:
      container-minor-and-patch:
        update-types:
          - minor
          - patch
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Etc/UTC
    open-pull-requests-limit: 2
    labels:
      - dependencies
    commit-message:
      prefix: deps(actions)
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
        patterns:
          - "*"
